import menClothe from "@/public/assets/menClothes/image 16.svg";
import menShoe1 from "@/public/assets/menFootwear/image 21.svg";
import menShoe2 from "@/public/assets/menFootwear/image 20.svg";

export const cards = [
  {
    id: 1,
    image: menClothe,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 2,
    image: menShoe1,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 3,
    image: menShoe2,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 4,
    image: menClothe,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 5,
    image: menShoe2,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 6,
    image: menClothe,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 7,
    image: menShoe1,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 8,
    image: menShoe2,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 9,
    image: menClothe,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 10,
    image: menShoe2,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 11,
    image: menShoe2,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 12,
    image: menClothe,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 13,
    image: menShoe1,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 14,
    image: menShoe2,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 15,
    image: menClothe,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
  {
    id: 16,
    image: menShoe2,
    price: 210,
    name: "Men's Jacket",
    discount: "-30%",
    rating: 4.5,
    reviews: "(3212 reviews)",
  },
];